buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

version = 'v2.1'
group = 'dev.aenco.mydash'
archivesBaseName = 'myDash-forge-1.18.2'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    mappings channel: 'official', version: '1.18.2'
}

sourceSets {
    main {
        java {
            srcDir '../../mydash-api/src/main/java'
            srcDir '../../mydash-core/src/main/java'
        }
        resources {
            srcDir '../../mydash-core/src/main/resources'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.2-40.2.21'
}

jar {
    archiveFileName = 'myDash-forge-1.18.2-v2.1.jar'
}

jar.finalizedBy('reobfJar')
