buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'

version = 'v2.1'
group = 'dev.aenco.mydash'
archivesBaseName = 'myDash-forge-1.16.5'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

minecraft {
    mappings channel: 'official', version: '1.16.5'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir '../../mydash-api/src/main/java'
            srcDir '../../mydash-core/src/main/java'
        }
        resources {
            srcDir 'src/main/resources'
            srcDir '../../mydash-core/src/main/resources'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.42'
}

jar {
    archiveFileName = 'myDash-forge-1.16.5-v2.1.jar'
    manifest {
        attributes([
            'Specification-Title': 'myDash',
            'Specification-Vendor': 'Aenco5523',
            'Specification-Version': '2.1',
            'Implementation-Title': project.name,
            'Implementation-Version': '2.1',
            'Implementation-Vendor': 'Aenco5523'
        ])
    }
}

jar.finalizedBy('reobfJar')
