name: myDash
version: '${version}'
main: dev.aenco.mydash.platform.paper1182.MyDashPaper1182
api-version: '1.18'
author: Aenco5523
website: https://github.com/Aenco5523/myDash
description: Self-hosted Minecraft server management dashboard and extensible API.
load: POSTWORLD
