plugins {
    id 'java'
}

group = 'dev.aenco.mydash'
version = 'v2.1'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.17.1'
}

sourceSets {
    main {
        java {
            srcDir '../../mydash-api/src/main/java'
            srcDir '../../mydash-core/src/main/java'
        }
        resources {
            srcDir '../../mydash-core/src/main/resources'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

processResources {
    filesMatching('plugin.yml') {
        expand version: '2.1'
    }
}

jar {
    archiveFileName = 'myDash-paper-1.20.1-v2.1.jar'
}
